# Project information
site_name: Gamedev Guide
site_description: >-
  Gamedev Guide: Programming with Unreal Engine, Houdini, Math, & Graphics
site_author: ikrimae
site_url: https://ikrima.dev/

# Repository
repo_name: ikrima/gamedevguide
repo_url: "https://github.com/ikrima/gamedevguide/"

# Copyright
copyright: Copyright &copy; 2016 - 2021 ikrima


# Configuration
docs_dir: content
use_directory_urls: true
strict: true

# nav:
#   - Home: index.md
#   - Open Source: opensource/index.md
#   - UE4: ue4guide/
#   - Math:
#       - Research Notes: math/research-notes/spectral-theory.md
#   - Graphics: graphics/index
#   - Houdini: houdini/index.md
#   - Programming: programming/index.md
#   - Computational Geometry: computational-geometry/chicken-scratch-notes.md
#   - Blog: blog/index.md


# Theme Config
# ----------- begin mkdocs-material -----------
theme:
  name: material
  # custom_dir: themes/material/material
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    # - navigation.expand
    # - toc.integrate
    # - navigation.indexes
  palette:
    scheme: slate
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
    # text: Open Sans
    # code: Hack
  # icon:
  #   logo: logo
  # favicon: _sitefiles/favicon.png

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ikrima
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ikrimae
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ikrima

# Plugins
plugins:
  - search:
      separator: '[\s\-\.\_]+'
      prebuild_index: true
  - git-revision-date-localized
  - awesome-pages:
      collapse_single_pages: true
  - progress
  # - minify:
  #     minify_html: true

# Extensions
markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - toc:
      permalink: "#"
      toc_depth: 6
  - codehilite:
      pygments_style: solarized-dark
      guess_lang: true
  # - markdown_katex:
  #     no_inline_svg: True
  #     insert_fonts_css: True
  #     # macro-file: macros.tex
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ikrima
      repo: gamedevguide
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

  # Builtins
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta

  # - pymdownx.keys
  # - pymdownx.snippets:
  #     check_paths: true

extra_javascript:
  - _sitefiles/katex/katex.min.js
  - _sitefiles/arithmatex-katex.js
extra_css:
  - _sitefiles/katex/katex.min.css
  - _sitefiles/mkdocs-extra.css

# Google Analytics
google_analytics:
  - UA-47614715-1
  - auto
# ----------- end mkdocs-material -----------

# ----------- begin cinder -----------
# theme:
#   name: null
#   custom_dir: themes/cinder/cinder
#   colorscheme: atom-one-dark-reasonable
#   highlightjs: true
#   hljs_languages:
#     - nim
# google_analytics: ['UA-47614715-1', 'ikrima.dev']
# shortcuts:
#     help: 191
#     next: 39
#     previous: 37
#     search: 83
# markdown_extensions:
#   - smarty
#   - sane_lists
#   - admonition
#   - toc:
#       permalink: "#"
#   - codehilite:
#       guess_lang: false
# ----------- end cinder -----------
