# Project information
site_name:        Gamedev Guide
site_author:      ikrimae
site_url:         https://ikrima.dev/
repo_name:        ikrima/gamedevguide
repo_url:         https://github.com/ikrima/gamedevguide
edit_uri:         https://github.com/ikrima/gamedevguide/edit/master/content
site_description: Programming with Unreal Engine, Houdini, Math, & Graphics
copyright:        Copyright &copy; 2016 - 2022 ikrima

# Configuration
docs_dir:           content
use_directory_urls: true
strict:             true

# nav:
#   - Home: index.md
#   - Open Source: opensource/index.md
#   - UE4: ue4guide/
#   - Math:
#       - Research Notes: math/research-notes/spectral-theory.md
#   - Graphics: graphics/index
#   - Houdini: houdini/index.md
#   - Programming: programming/index.md
#   - Computational Geometry: computational-geometry/chicken-scratch-notes.md
#   - Blog: blog/index.md


# Theme Config
theme:
  name: material
  # custom_dir: themes/material/material
  language: en
  # logo:    _sitefiles/logo.svg
  # favicon: _sitefiles/favicon.png
  icon:
    repo: fontawesome/brands/github
    # logo: fontawesome/solid/sticky-note
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: ayu
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # scheme: ayu
    # primary: indigo
    # accent: indigo
    # - scheme: default
    #   primary: indigo
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: slate
    #   primary: indigo
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  font:
    text: Nunito ###revisit
    code: Source Code Pro ###revisit
    # text: Open Sans
    # code: Source Code Pro
    # text: Roboto
    # code: JetBrains Mono
    # text: Roboto
    # code: Roboto Mono
    # text: Open Sans
    # code: Hack
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    # - navigation.expand
    # - navigation.indexes
    # - toc.integrate

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ikrima
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ikrimae
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ikrima
  analytics:
    provider: google
    property: G-VWCEPP5L4L

extra_css:
  # - _sitefiles/katex/katex.min.css # https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.css ###revisit
  - _sitefiles/mkdocs-extra.css
extra_javascript:
  # - _sitefiles/katex/katex.min.js # https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js ###revisit
  # - _sitefiles/arithmatex-katex.js ###revisit
  - _sitefiles/arithmatex-mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins/Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.sane_lists
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} ###revisit
      permalink: "#"
      toc_depth: 6
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index:     !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      user:                    ikrima
      repo:                    gamedevguide
      repo_url_shorthand:      true
      # repo_url_shortener:      true ###revisit
      # social_url_shorthand:    true ###revisit
      # social_url_shortener:    true ###revisit
      # normalize_issue_symbols: true ###revisit
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
      # block_tag: 'pre' ###revisit
  - pymdownx.highlight:
      pygments_style: solarized-dark
      linenums_style: pymdownx-inline
      guess_lang: true ###revisit
      extend_pygments_lang:
        - name: ue4c
          lang: bash
        - name: vex
          lang: glsl
  - pymdownx.inlinehilite:
      custom_inline:
        - name:   math
          class:  arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.superfences:
      preserve_tabs: true ###revisit
      custom_fences:
        - name:   math
          class:  arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic }} ###revisit {mode: generic, tag: pre}

  # - pymdownx.progressbar
  # - pymdownx.smartsymbols
  # - pymdownx.keys:
  #     key_map:
  #       click: "Click"
  #       left-click: "Left Click"
  #       right-click: "Right Click"
  #     separator: "\uff0b"
  # - pymdownx.striphtml
  # - pymdownx.snippets:
  #     check_paths: true
  # - pymdownx.escapeall:
  #     hardbreak: True
  #     nbsp: True
  # - markdown_katex:
  #     no_inline_svg: True
  #     insert_fonts_css: True
  #     # macro-file: macros.tex

plugins:
  - search:
      separator: '[\s\-\.\_]+'
  - git-revision-date-localized
  - awesome-pages:
      collapse_single_pages: false
  - progress
  # - minify:
  #     minify_html: true
