name: mkdocs-build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 4 * * *'

jobs:
  build:
    name: Build MkDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: false

      - name: Cache Artifacts
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN:    ikrima.dev
          CONFIG_FILE:      ./mkdocs.yml
          EXTRA_PACKAGES:   build-base
          # EXTRA_PACKAGES: build-base libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          REQUIREMENTS:     ./requirements.txt

# Vanilla deploy workflow
# permissions:
#   contents: write
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v3
#
#       - name: Set up Python 3.11
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11
#
#       - name: Cache Artifacts
#         uses: actions/cache@v3
#         with:
#           key: ${{ github.ref }}
#           path: .cache
#
#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip build
#           pip install -r requirements.txt
#
#       - name: Deploy MkDocs
#         run: mkdocs gh-deploy --force